name: navic_ss
description: A NavIC Navigation App with USB GNSS Support
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # CORE FUNCTIONALITY:
  flutter_map: ^5.0.0      # For OSM maps
  latlong2: ^0.9.0         # For coordinates
  geolocator: ^9.0.2       # For location services
  permission_handler: ^10.4.0  # For permissions

  # ENHANCEMENTS:
  flutter_svg: ^2.0.9      # For custom GNSS/satellite icons
  provider: ^6.0.5         # For state management

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
